micronaut:
  application:
    name: admin
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  server:
    cors:
      enabled: false
cassandra:
  default:
    contactPoint: '"localhost"'
    port: 9042
kafka.bootstrap.servers: localhost:9092
