micronaut:
  application:
    name: admin
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
cassandra:
  default:
    basic:
      contact-points:
        - ${CASSANDRA_POINT}
      load-balancing-policy:
        local-datacenter: datacenter1

kafka.bootstrap.servers: localhost:9092
